# Generated by Django 4.1 on 2022-08-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tag_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.course'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
